### PR TITLE
Add a Run all commands section to README

### PR DESCRIPTION
**Pull request by szepeviktor**
It takes a while to gather all possible commands.

### CODE REVIEW

**Comment by roborourke** [comment]
@szepeviktor sorry for the long delay getting to this, is the intention that this can be copied and run as a single command? The line breaks without backslashes might impact this.

**Comment by szepeviktor** [comment]
> is the intention that this can be copied and run as a single command? The line breaks without backslashes might impact this.

Yes.
Line breaks execute as a press of the ENTER key.
You can try it yourself.

**Review by roborourke — APPROVED** [review]
Happy with this addition as is, we can iterate if we want to do anything else docs wise to make this easier.

**Comment by roborourke** [comment]
Might depend on the specific shell used, but all good

**Pull request merged**
